Add output table to models.py
duets-ai/db_orm_model pull request #24
Opened 2023-11-22 00:22 UTC by arash-ans

This model will hold the blob file name of the output jsons generated. Minimal fields required since we can use the meeting_uuid to access language and participant information.

2023-11-30 21:11 UTC, mabadinakach requested changes
I dont think we need another table for this. Having another table might introduce latency issues for fetching the meeting. We can store the blob field in the meetings table. I want to hear others thoughts on this. 
@colmpat @FrankGuglielmo @alessandrobrra

2023-11-30 21:30 UTC, againTraviscodes commented
Grad team discussed, and we can develop with suggested change. See newest commit @mabadinakach @arash-ans @alessandrobrra @FrankGuglielmo @colmpat

2023-11-30 21:31 UTC, mabadinakach requested changes
nit:
a more appropiate name for the field could be feedback_blob

2023-11-30 22:51 UTC, alessandrobrra requested changes

2023-11-30 22:51 UTC, alessandrobrra commented on models.py
> +    json_blob = models.CharField(max_length=256, blank=False, null=False)
In addition to @mabadinakach comment, also set `blank` and `null` to True. Similar to `transcription_blob`

2023-12-01 00:23 UTC, mabadinakach approved these changes

2023-12-01 01:44 UTC, alessandrobrra approved these changes

2023-12-01 03:22 UTC, merged